name: autorun

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # 每 5 分钟运行一次

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run script on remote server
      run: |
        ssh -o StrictHostKeyChecking=no dakcl@s3.serv00.com "/home/dakcl/run.sh"
